# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_data?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678

# 配置日志
logging:
  level:
    root: warn
    top.kjwang.boot.mapper: trace