spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_data?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
  data:
    redis:
      host: 127.0.0.1 # Redis服务器地址
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）