spring:
  application:
    name: actuator
  boot:
    admin:
      client:
        url: http://localhost:8989
management:
  endpoint:
    health:
      show-details: always
    auditevents:
      web:
        exposure:
          include: '*'
      enabled: true
server:
  port: 9001