spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_task?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: JDBC #数据库存储quartz任务配置
    jdbc:
      initialize-schema: NEVER #自动初始化表结构，第一次启动的时候这里写always