spring:
  application:
    name: mail
  boot:
    admin:
      client:
        url: http://localhost:8989

  mail:
    host: smtp.qq.com
    username: 1729298243@qq.com
    password: tsdeaiqaeowyeedf
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          prot: 465    #465 587
        starttls:
          enable: true
          required: true
        ssl:
          enable: true
    default-encoding: UTF-8



management:
  endpoint:
    health:
      show-details: always
    auditevents:
      web:
        exposure:
          include: '*'
      enabled: true

server:
  port: 8002