spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_data?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 12345678
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password:

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 配置驼峰映射œ
  mapper-locations: classpath:mapper/*.xml  # 配置MyBatis的xml配置文件路径
  type-aliases-package: top.kjwang.domain  # 配置XML映射文件中指定的实体类别名路径