server:
  port: 8888

file:
  upload-path: /Users/wangkaijie/Desktop/upload/

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload-path}

minio:
  endPoint: http://127.0.0.1:9000
  accessKey: admin
  secretKey: 12345678

